/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SensorType {
  CURRENT, Current, VOLTAGE, Voltage, Depth, BatteryCurrent, WaterTemperature, Obstacle, Manual, TEMPERATURE, Temperature, CONDUCTIVITY, Conductivity, SALINITY, Salinity, WATER_DENSITY, SOUND_SPEED, SOUNDSPEED, Position, PRESSURE, RGB_CAM, RGBD_CAM, LIDAR, Course, Velocity, Heading, LinkQuality, CameraImage, BitrateAtReception, ReceivedPower, Altitude  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SensorType\",\"namespace\":\"eu.rawfie.uxv\",\"symbols\":[\"CURRENT\",\"Current\",\"VOLTAGE\",\"Voltage\",\"Depth\",\"BatteryCurrent\",\"WaterTemperature\",\"Obstacle\",\"Manual\",\"TEMPERATURE\",\"Temperature\",\"CONDUCTIVITY\",\"Conductivity\",\"SALINITY\",\"Salinity\",\"WATER_DENSITY\",\"SOUND_SPEED\",\"SOUNDSPEED\",\"Position\",\"PRESSURE\",\"RGB_CAM\",\"RGBD_CAM\",\"LIDAR\",\"Course\",\"Velocity\",\"Heading\",\"LinkQuality\",\"CameraImage\",\"BitrateAtReception\",\"ReceivedPower\",\"Altitude\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
