/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv.nested;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UxVHealthStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4107758118131842861L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UxVHealthStatus\",\"namespace\":\"eu.rawfie.uxv.nested\",\"fields\":[{\"name\":\"header\",\"type\":{\"type\":\"record\",\"name\":\"Header\",\"fields\":[{\"name\":\"sourceSystem\",\"type\":\"string\"},{\"name\":\"sourceModule\",\"type\":\"string\"},{\"name\":\"time\",\"type\":\"long\"}]}},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"UxVHealthStatusEnum\",\"symbols\":[\"OK\",\"Warning\",\"Critical\",\"Shutdown\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private eu.rawfie.uxv.nested.Header header;
   private eu.rawfie.uxv.nested.UxVHealthStatusEnum status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UxVHealthStatus() {}

  /**
   * All-args constructor.
   * @param header The new value for header
   * @param status The new value for status
   */
  public UxVHealthStatus(eu.rawfie.uxv.nested.Header header, eu.rawfie.uxv.nested.UxVHealthStatusEnum status) {
    this.header = header;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return header;
    case 1: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: header = (eu.rawfie.uxv.nested.Header)value$; break;
    case 1: status = (eu.rawfie.uxv.nested.UxVHealthStatusEnum)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'header' field.
   * @return The value of the 'header' field.
   */
  public eu.rawfie.uxv.nested.Header getHeader() {
    return header;
  }

  /**
   * Sets the value of the 'header' field.
   * @param value the value to set.
   */
  public void setHeader(eu.rawfie.uxv.nested.Header value) {
    this.header = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public eu.rawfie.uxv.nested.UxVHealthStatusEnum getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(eu.rawfie.uxv.nested.UxVHealthStatusEnum value) {
    this.status = value;
  }

  /**
   * Creates a new UxVHealthStatus RecordBuilder.
   * @return A new UxVHealthStatus RecordBuilder
   */
  public static eu.rawfie.uxv.nested.UxVHealthStatus.Builder newBuilder() {
    return new eu.rawfie.uxv.nested.UxVHealthStatus.Builder();
  }

  /**
   * Creates a new UxVHealthStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UxVHealthStatus RecordBuilder
   */
  public static eu.rawfie.uxv.nested.UxVHealthStatus.Builder newBuilder(eu.rawfie.uxv.nested.UxVHealthStatus.Builder other) {
    return new eu.rawfie.uxv.nested.UxVHealthStatus.Builder(other);
  }

  /**
   * Creates a new UxVHealthStatus RecordBuilder by copying an existing UxVHealthStatus instance.
   * @param other The existing instance to copy.
   * @return A new UxVHealthStatus RecordBuilder
   */
  public static eu.rawfie.uxv.nested.UxVHealthStatus.Builder newBuilder(eu.rawfie.uxv.nested.UxVHealthStatus other) {
    return new eu.rawfie.uxv.nested.UxVHealthStatus.Builder(other);
  }

  /**
   * RecordBuilder for UxVHealthStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UxVHealthStatus>
    implements org.apache.avro.data.RecordBuilder<UxVHealthStatus> {

    private eu.rawfie.uxv.nested.Header header;
    private eu.rawfie.uxv.nested.Header.Builder headerBuilder;
    private eu.rawfie.uxv.nested.UxVHealthStatusEnum status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.rawfie.uxv.nested.UxVHealthStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      if (other.hasHeaderBuilder()) {
        this.headerBuilder = eu.rawfie.uxv.nested.Header.newBuilder(other.getHeaderBuilder());
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UxVHealthStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.rawfie.uxv.nested.UxVHealthStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      this.headerBuilder = null;
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'header' field.
      * @return The value.
      */
    public eu.rawfie.uxv.nested.Header getHeader() {
      return header;
    }

    /**
      * Sets the value of the 'header' field.
      * @param value The value of 'header'.
      * @return This builder.
      */
    public eu.rawfie.uxv.nested.UxVHealthStatus.Builder setHeader(eu.rawfie.uxv.nested.Header value) {
      validate(fields()[0], value);
      this.headerBuilder = null;
      this.header = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'header' field has been set.
      * @return True if the 'header' field has been set, false otherwise.
      */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'header' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public eu.rawfie.uxv.nested.Header.Builder getHeaderBuilder() {
      if (headerBuilder == null) {
        if (hasHeader()) {
          setHeaderBuilder(eu.rawfie.uxv.nested.Header.newBuilder(header));
        } else {
          setHeaderBuilder(eu.rawfie.uxv.nested.Header.newBuilder());
        }
      }
      return headerBuilder;
    }

    /**
     * Sets the Builder instance for the 'header' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public eu.rawfie.uxv.nested.UxVHealthStatus.Builder setHeaderBuilder(eu.rawfie.uxv.nested.Header.Builder value) {
      clearHeader();
      headerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'header' field has an active Builder instance
     * @return True if the 'header' field has an active Builder instance
     */
    public boolean hasHeaderBuilder() {
      return headerBuilder != null;
    }

    /**
      * Clears the value of the 'header' field.
      * @return This builder.
      */
    public eu.rawfie.uxv.nested.UxVHealthStatus.Builder clearHeader() {
      header = null;
      headerBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public eu.rawfie.uxv.nested.UxVHealthStatusEnum getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public eu.rawfie.uxv.nested.UxVHealthStatus.Builder setStatus(eu.rawfie.uxv.nested.UxVHealthStatusEnum value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public eu.rawfie.uxv.nested.UxVHealthStatus.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public UxVHealthStatus build() {
      try {
        UxVHealthStatus record = new UxVHealthStatus();
        if (headerBuilder != null) {
          record.header = this.headerBuilder.build();
        } else {
          record.header = fieldSetFlags()[0] ? this.header : (eu.rawfie.uxv.nested.Header) defaultValue(fields()[0]);
        }
        record.status = fieldSetFlags()[1] ? this.status : (eu.rawfie.uxv.nested.UxVHealthStatusEnum) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
