/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.rawfie.uxv.nested;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UxVHealthStatusEnum {
  OK, Warning, Critical, Shutdown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UxVHealthStatusEnum\",\"namespace\":\"eu.rawfie.uxv.nested\",\"symbols\":[\"OK\",\"Warning\",\"Critical\",\"Shutdown\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
